[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  VITE_USE_BACKEND_PROXY = "true"

[build.secrets_scan]
  enabled = false

