[build]
  command = "npm run build"
  publish = "dist"

# Environment variables for Netlify deployment
[build.environment]
  VITE_USE_BACKEND_PROXY = "false"
  SECRETS_SCAN_ENABLED = "false"
  
# Add .env to ignored files during secrets scan
[build.secrets_scan]
  enabled = false

